name: Sort Mods Table

on:
  push:
    paths:
      - 'addedMods.md'
  pull_request:
    paths:
      - 'addedMods.md'

jobs:
  sort-table:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Sort mods table
        run: |
          python .github/workflows/sort_mods_table.py
          
      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT
          
      - name: Commit changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add addedMods.md
          git commit -m "Sort mods table alphabetically [skip ci]"
          git push