name: Update Timestamp

on:
  push:
    paths:
      - '**/*.properties'

jobs:
  update-timestamp:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get and process modified files
        run: |
          # Get the list of modified files directly into a variable (no temp file)
          MODIFIED_FILES=$(git diff --name-only HEAD^ HEAD | grep -E '\.properties$' || true)
          echo "Modified files: $MODIFIED_FILES"
          
          # Only proceed if there are modified files
          if [ -n "$MODIFIED_FILES" ]; then
            DATE=$(date '+%B %d, %Y, %H:%M UTC')
            
            # Process each file
            for file in $MODIFIED_FILES; do
              if [ -f "$file" ]; then
                echo "Processing file: $file"
                # Check if timestamp line already exists
                if grep -q "^### Last updated:" "$file"; then
                  # Update existing timestamp line
                  sed -i "s/^### Last updated:.*$/### Last updated: $DATE/" "$file"
                else
                  # Add timestamp line at the beginning of the file
                  sed -i "1i### Last updated: $DATE" "$file"
                fi
              else
                echo "File not found: $file"
              fi
            done
          else
            echo "No .properties files were modified"
          fi
      
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add *.properties
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update timestamps for modified files [skip ci]"
            git push
          fi